---
# this is the main playbook that will be executed

#### PLAY 1 ###########################################################################

- name: Create the ec2 instance
  hosts: localhost
  gather_facts: true
  become_user: "{{ localUser }}"
  become: true
  roles:
    - { role: create_vpc, tags: ["vpc"] }
    - { role: create_sg, tags: ["sg"] }
    - { role: create_keypair, tags: ["keypair"] }
    - { role: create_ec2, tags: ["ec2"] }
  vars_files:
    - vars/main.yml
    - vars/aws_credentials.yml

#### PLAY 2 ###########################################################################

- name: Install the web server
  hosts: ec2
  remote_user: ec2-user
  become: true
  roles:
    - { role: install_apache, tags: ["apache"] }
  vars_files:
    - vars/main.yml
    - vars/aws_credentials.yml
    
#######################################################################################