---

# this is the main playbook that will be executed

#### PLAY 1 ###########################################################################

- name: Create the ec2 instance
  hosts: localhost
  gather_facts: false
  become_user: "{{ localUser }}"
  become: true
  roles:
    - { role: destroy_ec2, tags: ["ec2"] }
    - { role: destroy_keypair, tags: ["keypair"] }
    - { role: destroy_sg, tags: ["sg"] }
    - { role: destroy_vpc, tags: ["vpc"] }

  vars_files:
    - vars/main.yml
    - vars/aws_credentials.yml