---

# this role terminates the ec2 instance

- name: Terminate EC2 instance
  amazon.aws.ec2_instance:
    state: absent
    instance_ids: "{{ instance_id }}"
    region: "{{ region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: result

- name: Display the result
  debug:
    var: result