---

# handlers file for main.yml

- name: Restart Apache2
  systemd:
    name: httpd
    state: restarted

###############################################################################

- name: Enable Apache2
  systemd:
    name: httpd
    enabled: yes